version: '3'

volumes:
  db-data:

services:
  
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'